Areas/Customer/Controllers/PieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BethanysPieShop.Models;
using BethanysPieShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BethanysPieShop.Controllers
{
    [Area("Customer")]
    public class PieController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
        }
        
        public IActionResult List(string category)
        {
            IEnumerable<Pie> pies;
            string currentCategory;

            if(string.IsNullOrEmpty(category))
            {
                pies = _pieRepository.AllPies.OrderBy(p => p.PieId);
                currentCategory = "All pies";
            }
            else
            {
                pies = _pieRepository.AllPies.Where(p => p.Category.CategoryName == category).OrderBy(p => p.PieId);
                currentCategory = _categoryRepository.AllCategories.FirstOrDefault(c => c.CategoryName == category).CategoryName;
            }
            return View(new PiesListViewModel
            {
                Pies = pies,
                CurrentCategory = currentCategory
            });
        }

        public IActionResult Details(int id)
        {
            var pie = _pieRepository.GetPieById(id);
            if (pie == null)
                return NotFound();
            return View(pie);
        }
    }
}

Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<li class="dropdown">
    <a asp-area="Customer" asp-controller="Pie"
       asp-action="Index"
       class="nav-item nav-link"
       data-toggle="dropdown">Pies<b class="caret"></b></a>
    <ul class="dropdown-menu">
        @foreach (var category in Model)
        {
        <li>
            <a class="nav-item nav-link" asp-area="Customer" asp-controller="Pie" asp-action="List"
               asp-route-category="@category.CategoryName">@category.CategoryName</a>
        </li>
    }
<li class="dropdown-divider"/>
        <li><a class="nav-item nav-link" asp-area="Customer" asp-controller="Pie" asp-action="List" asp-route-Category="">View all pies</a></li>
    </ul>
</li>